Q&A 添加 “有”  & MuteMenu 添加对禁言套餐填数字梗的制裁
MrWhoami/SDDDBotServices pull request #9
Opened 2020-08-12 07:47 UTC by broken-moon233

2020-08-12 08:28 UTC, MrWhoami requested changes
看一下 Review 改一下吧

2020-08-12 08:28 UTC, MrWhoami commented on src/main/kotlin/com/mrwhoami/qqservices/MuteMenu.kt
> +        if (total == 114514) || total == 364364 || total == 889464) {
这里不应该使用 `total`，甚至编译都过不了，因为 `total` 是上面那个 `time.Empty()` 作用域的临时变量，用于临时处理中文数字，这里应该用 `time.toInt()`

2020-08-12 08:28 UTC, MrWhoami commented on src/main/kotlin/com/mrwhoami/qqservices/QuestionAnswer.kt
> +            containsBotName(msgContent) && msgContent.contains("爬") ||
这里最好拿括号括一下

2020-08-12 08:28 UTC, MrWhoami commented on src/main/kotlin/com/mrwhoami/qqservices/QuestionAnswer.kt
> +                grp.sendMessage("你来帮我码代码就有了")
把 GitHub 链接加上就完美了

2020-08-12 08:36 UTC, broken-moon233 commented
改好了，感谢大佬指正

2020-08-12 08:42 UTC, MrWhoami requested changes
看上去没什么问题了，但是我觉得你还是应该 merge 一下我最新的 master branch
我刚加了一个 CI，就是让 Github 帮你编译一下看看有没有编译错误。你更新一下应该就有了

2020-08-12 08:44 UTC, MrWhoami requested changes

2020-08-12 08:44 UTC, MrWhoami commented on src/main/kotlin/com/mrwhoami/qqservices/MuteMenu.kt
> +        if (time.toInt() == 114514) || time.toInt() == 364364 || time.toInt() == 889464) {
不对，我刚才仔细看了一下，你这时间字符串长度都大于 5，所以会在前面那个 if 里面就卡掉。

2020-08-12 08:47 UTC, MrWhoami commented
CI 也 failed 了，你可以点 Details 进去看一下，看上去有个中文分号。我今天就到这里了，明天再继续

2020-08-12 23:19 UTC, MrWhoami requested changes

2020-08-12 23:19 UTC, MrWhoami commented on src/main/kotlin/com/mrwhoami/qqservices/MuteMenu.kt
> +        if (time.toInt() == 114514 || time.toInt() == 364364 || time.toInt() == 889464) {
事情是这样的，假设输入是 114514，我们来模拟一下代码的行为：

1. 读进消息，`val time : String = "114514`.
2. 在第45行，因为字符串“114514”的长度为6，大于5，进入这个 if
3. 在第50行，判断这个字符串有没有中文数字，显然“114514”这个字符串没有，进入 else 部分
4. 在第71行，进入 else，然后输出“你这个消息不对劲”，然后直接返回退出函数、

如上所示，根本不会进入你这个判断

2020-08-12 23:19 UTC, MrWhoami commented on src/main/kotlin/com/mrwhoami/qqservices/MuteMenu.kt
> +        if (time.toInt() == 114514 || time.toInt() == 364364 || time.toInt() == 889464) {
你有两个选择，一个是把你的if语句提到71行的 else 里，另一个是把前面45行的判断条件放宽，把大于5改成大于6.

2020-08-13 02:46 UTC, broken-moon233 commented on src/main/kotlin/com/mrwhoami/qqservices/MuteMenu.kt
> +        if (time.toInt() == 114514 || time.toInt() == 364364 || time.toInt() == 889464) {
改好了，感谢大佬

2020-08-13 03:21 UTC, MrWhoami approved these changes

2020-08-13 03:22 UTC, MrWhoami commented
这回应该可以了。其实如果能不用网页编辑而，是用电脑本地的编辑器编辑，之后统一commit更好，因为这样就不会有这么多不知所云的 commit 记录了。不过这我也不强求就是了。

2020-08-13 03:23 UTC, merged